# Generated by Django 4.1.13 on 2024-05-26 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
