# Generated by Django 4.1.13 on 2024-05-26 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_alter_video_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='uu_id',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
