# Generated by Django 4.1.13 on 2024-05-26 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_alter_video_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='video',
            name='modified',
            field=models.DateTimeField(),
        ),
    ]
