# Generated by Django 4.1.13 on 2024-05-26 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_alter_video_created_alter_video_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
