# Generated by Django 4.1.13 on 2024-05-26 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_video_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='sector',
            field=models.TextField(blank=True, choices=[('Grado Educativo', 'Grado Educativo'), ('Educación Libre', 'Educación Libre')], null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='type',
            field=models.TextField(blank=True, choices=[('Fisica', 'Fisica'), ('Matematicas', 'Matematicas'), ('Programacion', 'Programacion'), ('Filosofia', 'Filosofia'), ('Psicologia', 'Psicologia'), ('Ingles', 'Ingles')], null=True),
        ),
    ]
