# Generated by Django 4.1.13 on 2024-05-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_video_sector_alter_video_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='sector',
            field=models.TextField(choices=[('Grado Educativo', 'Grado Educativo'), ('Educación Libre', 'Educación Libre')], default='Educación Libre'),
        ),
    ]
